use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :sre, Sre.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "sre.com", port: 443],
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :warn, backends: [Rollbax.Logger]

# We configure the Rollbax.Logger backend.
config :logger, Rollbax.Logger,
  level: :error

config :sre,
  photo_cdn: "https://sre-production.imgix.net/",
  from_email: "info@sre.com",
  to_email: "info@sre.com",
  ip_location_key: "SAKB68XT85854ETM999Z",
  tracking_enabled: true,
  allow_indexing: true,
  office_emails: %{
    ca: "sandiego@sre.com",
    hi: "hawaii@sre.com",
    az: "arizona@sre.com",
  }

# Show warnings if environment variables are missing
if is_nil(System.get_env("NEW_RELIC_LICENSE_KEY")) do
  IO.warn "Missing environment variable NEW_RELIC_LICENSE_KEY"
end

config :new_relic,
  application_name: "SRE.com",
  license_key: System.get_env("NEW_RELIC_LICENSE_KEY"),
  poll_interval: 30_000 # push data to NewRelic once per 1 minute

config :ueberauth, Ueberauth,
  providers: [
    auth0: {Ueberauth.Strategy.Auth0, [
      callback_url: "https://sre.com/auth/auth0/callback"
    ]}
  ]

config :sre, Sre.Mailer,
  adapter: Bamboo.SendgridAdapter,
  api_key: System.get_env("SENDGRID_API_KEY")
